### ISSUE TITLE
Terrible performance when the vertical size of the scrollable area is big

### ISSUE THREAD

**Issue by vtdmhd** [DMagic1/KSP_Contract_Window#13]
With 14 active contracts during flights the CPU is constantly loaded when the window is displayed (even if its size is small). This cripples the overall performance. Disabling transparency (by replacing the texture) does not help. Hiding the window brings everything back to normal, as does hiding/minimizing most contracts.

**Comment by DMagic1** [comment]
Fixed by 075579edca00a2e76fe04b76c49024d8deef16c0
