### ISSUE TITLE
Ability to add custom objectives to a mission

### ISSUE THREAD

**Issue by hoylemd** [DMagic1/KSP_Contract_Window#24]
I don't know how reasonable this would be, but it would be really great if I could add my own objectives to missions.  I don't expect that they would be integrated with the game in any way.

Example:
I have a mission with a couple of contracts to land on the Mun.  I add them all to a mission that I name "Kerpollo 11".  In addition to those contracts that I will get rewards for, I want to remember to plant a flag.

I'd like the ability to add custom objectives like this to a mission.

A more MVP version of this could be as simple as a description field on missions, so I can at least write those things down in-game.

**Comment by DMagic1** [comment]
I want Contracts Window to stay focused on monitoring contracts only.

I have been working on something else more focused on managing all aspects of a mission for each vessel: assigning contracts, managing crew, adding notes, adding checklist items (both built in types, and custom types that would require manually setting it to complete), managing all of the on-board experiments and data, keeping a log of a vessel's activities, and probably more.

It's still a [work-in-progress](https://github.com/DMagic1/KSP_Vessel_Manager) (I'm waiting for 1.1 and its new UI before getting anything in-game), but there is a significant framework already complete. Now I just need to think up of a snappy name for it.

**Comment by hoylemd** [comment]
Oh awesome! Very much looking forward to that. If you need testers, I'm in!
