### ISSUE TITLE
Replace Stock Toolbar issue

### ISSUE THREAD

**Issue by Altrue** [DMagic1/KSP_Contract_Window#33]
Choosing the "Replace Stock Toolbar" option does indeed replace the Stock Contract window in the Stock Toolbar.

The problem is that this change is only temporary. When reloading your game later on, the Stock Contract window is the one that shows up when you click the Contracts button on the toolbar, and the "KSP Contract Window" (this mod) is nowhere to be found, same for its toolbar icon. 

You effectively have no way to bring the mod window back up, unless you edit persistent.cfg to have the window show up, which enables you to disable the setting.

**Comment by DMagic1** [comment]
Fixed in 7.2.
