### ISSUE TITLE
Enhancement:  ability to list available contracts

### ISSUE THREAD

**Issue by Atario** [DMagic1/KSP_Contract_Window#37]
It would help me a lot to see the reward/penalty totals for all the currently proposed contracts, so I can sort them to pick and choose which to accept in order to rake in the spacebux.  Currently doing this by laboriously typing the numbers in by hand to a spreadsheet, like a caveman or something

**Comment by Kerbas-ad-astra** [comment]
CapCom (also by DMagic) has the feature of listing available contracts in-flight, though I don't know offhand what sorting criteria it has.

**Comment by DMagic1** [comment]
Contracts Window plus only shows active contracts, but it can sort those based on rewards.

CapCom can sort by reward, too, using any of the three types. I think it totals up the reward value for the contract and all of its parameters.

**Comment by Atario** [comment]
Thanks, I just checked that out.  Not bad, but it doesn't actually show you the totals it's sorting by… also I'm not convinced the sorting is always correct 😟
