### ISSUE TITLE
"Contract Missions" sub-window incorrect size

### ISSUE THREAD

**Issue by Galenmacil** [DMagic1/KSP_Contract_Window#49]
Aside from "All Contracts", the window only fits the first 4 custom defined groups:

![Contracts+](https://user-images.githubusercontent.com/19394274/60780190-61db8780-a10b-11e9-8999-1d56d7f5d6f5.png)

Notice the "Contract Missions" window showing "All Contracts", "Minmus", "Mun", "Eve" and "Duna" correctly while "Tourist", "Moho" and "Kerbin" are below and outside the window.

**Comment by Galenmacil** [comment]
Seems to fix itself after reloading a game... Not a major issue for sure.

**Comment by DMagic1** [comment]
Fixed in version 9.3.
