### ISSUE TITLE
Display differences between stock app and Contracts Window +

### ISSUE THREAD

**Issue by jrossignol** [DMagic1/KSP_Contract_Window#9]
Raised on the forums (see [this post] (http://forum.kerbalspaceprogram.com/threads/91034-0-90-Contracts-Window-v3-0-1-2-15?p=1658999&viewfull=1#post16589990), but think it might've been missed:

I've got a couple bugs/requests for you. Head over to [this post] (http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-5-0-2015-01-08?p=1658981&viewfull=1#post1658981) in the Contract Configurator thread for the background.

1. When a parameter has no title (I assume the check is for null/empty), the stock contracts app does not display that parameter OR any of its child parameters. I rely on this behaviour to secret away and hide a parameter that needs to be there to display the orbits, but may not be desirable as an actual contract parameter. Would it be possible to do the same logic in Contracts Window + to be consistent with stock?
1. In the stock app, when a parameter with child parameters is completed, it stops displaying the child parameters. To be honest the behaviour is annoying, but since I have to assume users are potentially using the stock app, I have many cases where I change the parameter title to show some details from the children when it's complete (so the user can still see it). This results in it getting displayed twice in Contracts Window +. So again - could Contracts Window + be changed to behave like stock (not because I like the behaviour, but for consistency).

**Comment by DMagic1** [comment]
Yeah, I saw it. I just didn't want to make anything but the minimum amount of changes for that bugfix update.

Both suggestions should be easy to implement.

Does the stock app continue to display the child parameters if disableOnStateChange is set to false? It would make sense to check for that as well when deciding whether or not to display child parameters, regardless of how the stock app works.

**Comment by jrossignol** [comment]
It ignores disableOnStateChange (or the disabled attributed) for these purposes.  If a disableOnStateChange = false parameter goes from Completed => Inactive, the child parameters reappear.  So it appears to be based purely on the current state.
